version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  psqlledger:
    image: psqlledger:latest
    #build:
    #  context: ../docker
    #  dockerfile: Dockerfile
    container_name: psqlledger
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bank
    ports:
      - "8080:8080"
