// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Account struct {
	ID        int64          `json:"id"`
	Username  string         `json:"username"`
	Balance   int64          `json:"balance"`
	Email     sql.NullString `json:"email"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Transaction struct {
	ID          int64         `json:"id"`
	FromAccount sql.NullInt64 `json:"from_account"`
	ToAccount   sql.NullInt64 `json:"to_account"`
	Amount      sql.NullInt64 `json:"amount"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}
