// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Account struct {
	ID        int64 
	Username  string 
	Balance   int64 
	Email     sql.NullString
	CreatedAt sql.NullTime
}

type Transaction struct {
	ID          int64
	FromAccount sql.NullInt64
	ToAccount   sql.NullInt64
	Amount      sql.NullInt64
	CreatedAt   sql.NullTime
}
